# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTaxHistory():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_taxHistory(self):
    # Test name: TaxHistory
    # Step # | name | target | value
    # 1 | open | https://revenue.stlouisco.com/IAS/SearchInput.aspx | 
    #  Real Estate Search page
    self.driver.get("https://revenue.stlouisco.com/IAS/SearchInput.aspx")
    # 2 | waitForElementPresent | css=.col-md-5 | 30000
    # Wait/verify Locator Number SrchFld Present
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".col-md-5")))
    # 3 | type | id=ctl00_MainContent_tboxLocatorNum | 15G430064
    # Write Locator Number
    self.driver.find_element(By.ID, "ctl00_MainContent_tboxLocatorNum").send_keys("15G430064")
    # 4 | click | id=ctl00_MainContent_butFind | 
    self.driver.find_element(By.ID, "ctl00_MainContent_butFind").click()
    # 5 | click | css=td:nth-child(3) | 
    # PositiveSearchResultsPage
    self.driver.find_element(By.CSS_SELECTOR, "td:nth-child(3)").click()
    # 6 | click | id=ctl00_MainContent_NavLinks1_TaxHistoryLB | 
    self.driver.find_element(By.ID, "ctl00_MainContent_NavLinks1_TaxHistoryLB").click()
    # 7 | waitForElementPresent | css=.row > .font-weight-bold | 30000
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".row > .font-weight-bold")))
  
